'use client';

import React, { useState, useEffect } from 'react';
import { DataService } from '@/services/data';
import { Case, CaseDocument } from '@/types';
import { Card } from '@/components/Card';
import { ArrowLeft, FileText, Download, Trash2, File, UploadCloud, Search, Filter, AlertCircle, ExternalLink } from 'lucide-react';
import AppLayout from '@/components/Layout';
import Link from 'next/link';
import { useParams } from 'next/navigation';

export default function CaseDocuments() {
  // Fix: Safely extract ID using the hook
  const params = useParams();
  const caseId = params?.id as string;

  const [caseData, setCaseData] = useState<Case | null>(null);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState<'ALL' | 'INVOICE' | 'UPLOAD'>('ALL');

  useEffect(() => {
    // Fix: Check if caseId exists before fetching
    if (caseId) {
        fetchCaseDetails();
    }
  }, [caseId]);

  const fetchCaseDetails = async () => {
    if (!caseId) return;
    
    try {
      const data = await DataService.getCase(caseId);
      setCaseData(data);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = (doc: CaseDocument) => {
    if (!caseData) return;

    if (doc.type === 'INVOICE') {
        // Generate a nice HTML Invoice
        const content = `
<!DOCTYPE html>
<html>
<head>
    <title>${doc.name}</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; max-width: 800px; margin: 0 auto; border: 1px solid #eee; }
        .header { border-bottom: 2px solid #2563EB; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
        .logo { font-size: 24px; font-weight: bold; color: #2563EB; }
        .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 40px; }
        .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 4px; }
        .value { font-size: 16px; font-weight: 500; }
        .amount-box { background: #F3F4F6; padding: 20px; border-radius: 8px; text-align: right; }
        .amount-label { font-size: 14px; color: #666; }
        .amount-value { font-size: 36px; font-weight: bold; color: #111; }
        .status { display: inline-block; padding: 6px 12px; background: #DCFCE7; color: #166534; border-radius: 20px; font-size: 14px; font-weight: 600; margin-top: 10px; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; text-align: center; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">LegalFlow</div>
        <div>Official Receipt</div>
    </div>
    
    <div class="meta-grid">
        <div>
            <div class="label">Billed To</div>
            <div class="value">${caseData.clientName}</div>
            <div style="font-size: 14px; color: #666; margin-top: 4px;">${caseData.caseNumber}</div>
        </div>
        <div style="text-align: right;">
            <div class="label">Invoice Details</div>
            <div class="value">${doc.name}</div>
            <div style="font-size: 14px; color: #666; margin-top: 4px;">Date: ${new Date(doc.createdAt).toLocaleDateString()}</div>
        </div>
    </div>

    <div class="amount-box">
        <div class="amount-label">Total Amount Paid</div>
        <div class="amount-value">$${caseData.value.toLocaleString()}</div>
        <div class="status">PAID IN FULL</div>
    </div>

    <div class="footer">
        Generated by LegalFlow Practice Management System<br>
        This is a computer generated document.
    </div>
</body>
</html>`;
        
        const blob = new Blob([content], { type: 'text/html' });
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${doc.name.replace(/\s/g, '_')}.html`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
    } else if (doc.url) {
        // Open Cloudinary URL
        window.open(doc.url, '_blank');
    } else {
        alert("Document URL missing.");
    }
  };

  const handleDelete = async (docId: string) => {
      if(!confirm("Are you sure you want to delete this document?")) return;
      try {
          await DataService.deleteCaseDocument(docId);
          fetchCaseDetails(); 
      } catch (e) {
          alert("Failed to delete document");
      }
  };

  const filteredDocs = caseData?.documents?.filter(doc => {
      const matchesSearch = doc.name.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesFilter = filterType === 'ALL' || doc.type === filterType;
      return matchesSearch && matchesFilter;
  }) || [];

  const invoiceCount = caseData?.documents?.filter(d => d.type === 'INVOICE').length || 0;
  const uploadCount = caseData?.documents?.filter(d => d.type === 'UPLOAD').length || 0;

  if (loading) {
      return (
          <AppLayout>
              <div className="flex justify-center items-center h-full">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
              </div>
          </AppLayout>
      );
  }

  if (!caseData) {
      return (
          <AppLayout>
              <div className="p-8 text-center">Case not found</div>
          </AppLayout>
      );
  }

  return (
    <AppLayout>
      <div className="p-8 max-w-6xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center space-x-4 mb-2">
            <Link href={`/cases/${caseData.id}`} className="p-2 hover:bg-slate-200 rounded-full transition-colors text-slate-600">
                <ArrowLeft className="w-6 h-6" />
            </Link>
            <div>
                <h1 className="text-2xl font-bold text-slate-900">Document Repository</h1>
                <p className="text-slate-500">Managing files for {caseData.caseNumber}</p>
            </div>
        </div>

        {/* Info Banner */}
        <div className="bg-blue-50 border border-blue-100 rounded-lg p-4 flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-blue-600 mt-0.5 flex-shrink-0" />
            <div className="text-sm text-blue-800">
                <p className="font-semibold">Secure Cloud Storage</p>
                <p>Files uploaded here are stored securely in the cloud. Click the view button to access the actual file content.</p>
            </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 flex items-center justify-between">
                <div>
                    <p className="text-sm font-medium text-slate-500">Total Files</p>
                    <p className="text-2xl font-bold text-slate-900">{caseData.documents?.length || 0}</p>
                </div>
                <div className="p-3 bg-blue-50 text-blue-600 rounded-lg">
                    <File className="w-6 h-6" />
                </div>
            </div>
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 flex items-center justify-between">
                <div>
                    <p className="text-sm font-medium text-slate-500">Invoices Generated</p>
                    <p className="text-2xl font-bold text-slate-900">{invoiceCount}</p>
                </div>
                <div className="p-3 bg-green-50 text-green-600 rounded-lg">
                    <FileText className="w-6 h-6" />
                </div>
            </div>
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 flex items-center justify-between">
                <div>
                    <p className="text-sm font-medium text-slate-500">User Uploads</p>
                    <p className="text-2xl font-bold text-slate-900">{uploadCount}</p>
                </div>
                <div className="p-3 bg-purple-50 text-purple-600 rounded-lg">
                    <UploadCloud className="w-6 h-6" />
                </div>
            </div>
        </div>

        {/* Main Content */}
        <Card className="min-h-[500px]">
            <div className="p-4 border-b border-slate-100 bg-slate-50/50 flex flex-col md:flex-row justify-between gap-4">
                <div className="relative flex-1">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 w-5 h-5" />
                    <input 
                        type="text" 
                        placeholder="Search by file name..." 
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="w-full pl-10 pr-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none"
                    />
                </div>
                <div className="flex items-center space-x-2">
                    <Filter className="w-4 h-4 text-slate-500" />
                    <select 
                        value={filterType}
                        onChange={(e) => setFilterType(e.target.value as any)}
                        className="border border-slate-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                    >
                        <option value="ALL">All Documents</option>
                        <option value="INVOICE">Invoices Only</option>
                        <option value="UPLOAD">Uploads Only</option>
                    </select>
                </div>
            </div>

            <div className="p-0">
                {filteredDocs.length > 0 ? (
                    <div className="divide-y divide-slate-100">
                        {filteredDocs.map((doc) => (
                            <div key={doc.id} className="p-4 flex items-center justify-between hover:bg-slate-50 transition-colors group">
                                <div className="flex items-center space-x-4">
                                    <div className={`p-3 rounded-lg ${doc.type === 'INVOICE' ? 'bg-green-100 text-green-600' : 'bg-blue-100 text-blue-600'}`}>
                                        {doc.type === 'INVOICE' ? <FileText className="w-6 h-6" /> : <File className="w-6 h-6" />}
                                    </div>
                                    <div>
                                        <h4 className="font-medium text-slate-900">{doc.name}</h4>
                                        <p className="text-sm text-slate-500 flex items-center gap-2">
                                            <span>{doc.size}</span>
                                            <span>•</span>
                                            <span>Uploaded by {doc.createdBy}</span>
                                            <span>•</span>
                                            <span>{new Date(doc.createdAt).toLocaleString()}</span>
                                        </p>
                                    </div>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <button 
                                        onClick={() => handleDownload(doc)}
                                        className="flex items-center space-x-1 px-3 py-1.5 text-sm font-medium text-blue-600 bg-blue-50 rounded-lg hover:bg-blue-100 transition-colors"
                                    >
                                        {doc.type === 'INVOICE' ? <Download className="w-4 h-4" /> : <ExternalLink className="w-4 h-4" />}
                                        <span className="hidden sm:inline">{doc.type === 'INVOICE' ? 'Download' : 'View File'}</span>
                                    </button>
                                    <button 
                                        onClick={() => handleDelete(doc.id)}
                                        className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                                        title="Delete"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                ) : (
                    <div className="flex flex-col items-center justify-center py-16 text-slate-500">
                        <File className="w-16 h-16 text-slate-200 mb-4" />
                        <p className="text-lg font-medium">No documents found</p>
                        <p className="text-sm">Upload files from the case details page to see them here.</p>
                    </div>
                )}
            </div>
        </Card>
      </div>
    </AppLayout>
  );
}